var = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(var))
print('Só tem espaços?', var.isspace())
print('É um numero? ', var.isnumeric())
print('É alfabético? ', var.isalpha())
print('É alfanumerico? ', var.isalnum())
print('Está em maiúsculo? ', var.isupper())
print('Está em minusculo? ', var.islower())
print('Está capitalizado?', var.istitle())
