num = int(input('Uma distancia em metros: '))
print(f'A medida de {num} corresponde a ')
print(f'{num/1000} KM')
print(f'{num/100} hm')
print(f'{num/10} dam')
print(f'{num*10} dm')
print(f'{num*100} cm')
print(f'{num*1000} mm')