# EXISTEM 4 PRINCIPAIS ESTILOS:
#0 SEM ESTILO
#1 NEGRITO
#4 SUBLINHADO
#7 NEGATIVE (TROCA CORES)

# \33[0:33:44m - ENTRE [ e m - inserir 0, 1, 2 ou 3 codigos
#STYLE (NORMAL, NEGRITO, SUBLINHAD)
#TEXT (COR DO TEXTO
#BACKGROUND (COR DO FUNDO)
# 0 - NORMAL
# 33 - CODIGO DO TEXTO
# 44 - CODIGO DO FUNDO
#
#
#
#
#
print('\033[7;33;44Olá Mundo')
